### ISSUE TITLE
connect error on kali linux

### ISSUE THREAD

**Issue by Narhty** [OpenVPN/openvpn#552] opened 2024-05-14 11:10 UTC
024-05-14 19:55:48 Restart pause, 1 second(s)
2024-05-14 19:55:49 TCP/UDP: Preserving recently used remote address: [AF_INET]18.202.168.160:1194
2024-05-14 19:55:49 Socket Buffers: R=[212992->212992] S=[212992->212992]
2024-05-14 19:55:49 UDPv4 link local: (not bound)
2024-05-14 19:55:49 UDPv4 link remote: [AF_INET]18.202.168.160:1194
2024-05-14 19:55:50 TLS: Initial packet from [AF_INET]18.202.168.160:1194, sid=6072fcc5 df7b98a0
2024-05-14 19:55:50 VERIFY ERROR: depth=1, error=self-signed certificate in certificate chain: CN=ChangeMe, serial=425397202556807641543660048237946304772097879576
2024-05-14 19:55:50 OpenSSL: error:0A000086:SSL routines::certificate verify failed:
2024-05-14 19:55:50 TLS_ERROR: BIO read tls_read_plaintext error
2024-05-14 19:55:50 TLS Error: TLS object -> incoming plaintext read error
2024-05-14 19:55:50 TLS Error: TLS handshake failed
2024-05-14 19:55:50 SIGUSR1[soft,tls-error] received, process restarting
2024-05-14 19:55:50 Restart pause, 1 second(s)
2024-05-14 19:55:51 TCP/UDP: Preserving recently used remote address: [AF_INET]18.202.168.160:1194
2024-05-14 19:55:51 Socket Buffers: R=[212992->212992] S=[212992->212992]
2024-05-14 19:55:51 UDPv4 link local: (not bound)
2024-05-14 19:55:51 UDPv4 link remote: [AF_INET]18.202.168.160:1194
2024-05-14 19:55:51 TLS: Initial packet from [AF_INET]18.202.168.160:1194, sid=0a4fd461 973221bf
2024-05-14 19:55:52 VERIFY ERROR: depth=1, error=self-signed certificate in certificate chain: CN=ChangeMe, serial=425397202556807641543660048237946304772097879576
2024-05-14 19:55:52 OpenSSL: error:0A000086:SSL routines::certificate verify failed:
2024-05-14 19:55:52 TLS_ERROR: BIO read tls_read_plaintext error
2024-05-14 19:55:52 TLS Error: TLS object -> incoming plaintext read error
2024-05-14 19:55:52 TLS Error: TLS handshake failed
2024-05-14 19:55:52 SIGUSR1[soft,tls-error] received, process restarting
2024-05-14 19:55:52 Restart pause, 1 second(s)
2024-05-14 19:55:53 TCP/UDP: Preserving recently used remote address: [AF_INET]18.202.168.160:1194
2024-05-14 19:55:53 Socket Buffers: R=[212992->212992] S=[212992->212992]
2024-05-14 19:55:53 UDPv4 link local: (not bound)
2024-05-14 19:55:53 UDPv4 link remote: [AF_INET]18.202.168.160:1194
2024-05-14 19:55:53 TLS: Initial packet from [AF_INET]18.202.168.160:1194, sid=0ac737fb 52f1304e
2024-05-14 19:55:53 VERIFY ERROR: depth=1, error=self-signed certificate in certificate chain: CN=ChangeMe, serial=425397202556807641543660048237946304772097879576
2024-05-14 19:55:53 OpenSSL: error:0A000086:SSL routines::certificate verify failed:
2024-05-14 19:55:53 TLS_ERROR: BIO read tls_read_plaintext error
2024-05-14 19:55:53 TLS Error: TLS object -> incoming plaintext read error
2024-05-14 19:55:53 TLS Error: TLS handshake failed
2024-05-14 19:55:53 SIGUSR1[soft,tls-error] received, process restarting
2024-05-14 19:55:53 Restart pause, 1 second(s)
2024-05-14 19:55:54 TCP/UDP: Preserving recently used remote address: [AF_INET]18.202.168.160:1194
2024-05-14 19:55:54 Socket Buffers: R=[212992->212992] S=[212992->212992]
2024-05-14 19:55:54 UDPv4 link local: (not bound)
2024-05-14 19:55:54 UDPv4 link remote: [AF_INET]18.202.168.160:1194
^C2024-05-14 19:55:54 event_wait : Interrupted system call (fd=-1,code=4)
2024-05-14 19:55:54 SIGTERM received, sending exit notification to peer
2024-05-14 19:55:54 TLS: Initial packet from [AF_INET]18.202.168.160:1194, sid=84d2b115 256060bb
2024-05-14 19:55:55 VERIFY ERROR: depth=1, error=self-signed certificate in certificate chain: CN=ChangeMe, serial=425397202556807641543660048237946304772097879576
2024-05-14 19:55:55 OpenSSL: error:0A000086:SSL routines::certificate verify failed:
2024-05-14 19:55:55 TLS_ERROR: BIO read tls_read_plaintext error
2024-05-14 19:55:55 TLS Error: TLS object -> incoming plaintext read error
2024-05-14 19:55:55 TLS Error: TLS handshake failed
2024-05-14 19:55:55 Converting soft SIGUSR1 received during exit notification to SIGTERM
2024-05-14 19:55:55 SIGTERM[soft,exit-with-notification] received, process exiting

I just tried to connect openvpn in my kali linux,.
I also tried deleting and reinstalling to fix this problem, but it couldn't solve it.
plz help me

**Comment by ordex** [comment] 2024-05-14 11:25
> 2024-05-14 19:55:55 VERIFY ERROR: depth=1, error=self-signed certificate in certificate chain: CN=ChangeMe, serial=425397202556807641543660048237946304772097879576

this is telling you what the problem is. Either you use a proper PKI (with CA and certs signed accordingly) or you can have a look at `--peer-fingerprint`.

In any case this is not a bug report, therefore I am closing this issue.

If you need assistance with usage and errors, please reach out on the forum or the mailing list.

**Comment by Twin1ght** [comment] 2024-05-15 11:27
I think i have the same problem. Have you found a solution?

**Comment by Narhty** [comment] 2024-05-15 11:32
nah, not tet im still finding solution.
If i find solution ill send a mail for you

네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>, ***@***.***>
날짜: 2024. 5. 15 오후 8:28:03
제목: Re: [OpenVPN/openvpn] connect error on kali linux (Issue #552)

I think i have the same problem. Have you found a solution?

**Comment by Twin1ght** [comment] 2024-05-15 11:56
I want to clarify. Are you trying to connect to tryhackme too?

**Closed** 2024-05-15 12:08 UTC

**Comment by Narhty** [comment] 2024-05-15 12:10
Yeah I'm trying to keep in touch, but they dont help at all
-----Original Message-----

**Comment by Twin1ght** [comment] 2024-05-15 12:12
But why is there no information about this error on the internet

**Comment by Twin1ght** [comment] 2024-05-15 12:13
yes, ordex, if you know the solution please explain in more detail

**Comment by ordex** [comment] 2024-05-15 12:16
This is a bug tracker, please stop spamming as if it was your support chat.
If you want to discuss and talk to people, please join the openvpn IRC channel.

If you continue spamming, I will have to delete the ticket.
