### ISSUE TITLE
auth-user-pass-verify and pending authentication with openurl doesn't work

### ISSUE THREAD

**Issue by jkroepke** [OpenVPN/openvpn#261] opened 2023-02-24 20:49 UTC
**Describe the bug**
I enabled `auth-user-pass-verify .. via-file` on my server. The program write 3 lines to auth_pending_file and returns exit code 2. The server is advertising authentication deferred, but the client will never get the informations.

**To Reproduce**
Setup a OpenVPN server. 

**/usr/local/bin/vpn-auth**
```sh
#!/usr/bin/env bash

printf '100\nopenurl\nOPEN_URL:https://google.de' > "$auth_pending_file"
exit 2

```

**server.conf**
```
script-security 3
auth-user-pass-verify /usr/local/bin/vpn-auth via-file
```

**Expected behavior**

**Version information (please complete the following information):**
Server
 - OS: [e.g. Ubuntu 22.04] Alpine Edge
 - OpenVPN version: [e.g. 2.5.8] 2.6.0

Client
 - OS: [e.g. Ubuntu 22.04] Windows 10
 - OpenVPN version: [e.g. 2.5.8] 2.6.0

**Additional context**

Server Logs:

```
tests-openvpn26-1  | 2023-02-24 20:22:50 us=874624 172.19.0.1:53469 peer info: IV_VER=2.6.0
tests-openvpn26-1  | 2023-02-24 20:22:50 us=874726 172.19.0.1:53469 peer info: IV_PLAT=win
tests-openvpn26-1  | 2023-02-24 20:22:50 us=874795 172.19.0.1:53469 peer info: IV_TCPNL=1
tests-openvpn26-1  | 2023-02-24 20:22:50 us=874881 172.19.0.1:53469 peer info: IV_MTU=1600
tests-openvpn26-1  | 2023-02-24 20:22:50 us=874912 172.19.0.1:53469 peer info: IV_NCP=2
tests-openvpn26-1  | 2023-02-24 20:22:50 us=874953 172.19.0.1:53469 peer info: IV_CIPHERS=AES-256-GCM:AES-128-GCM
tests-openvpn26-1  | 2023-02-24 20:22:50 us=875040 172.19.0.1:53469 peer info: IV_PROTO=478
tests-openvpn26-1  | 2023-02-24 20:22:50 us=875071 172.19.0.1:53469 peer info: IV_LZO_STUB=1
tests-openvpn26-1  | 2023-02-24 20:22:50 us=875100 172.19.0.1:53469 peer info: IV_COMP_STUB=1
tests-openvpn26-1  | 2023-02-24 20:22:50 us=875131 172.19.0.1:53469 peer info: IV_COMP_STUBv2=1
tests-openvpn26-1  | 2023-02-24 20:22:50 us=875196 172.19.0.1:53469 peer info: IV_GUI_VER=OpenVPN_GUI_11
tests-openvpn26-1  | 2023-02-24 20:22:50 us=875276 172.19.0.1:53469 peer info: IV_SSO=openurl,webauth,crtext
tests-openvpn26-1  | 2023-02-24 20:34:17 us=994581 172.19.0.1:60049 SENT CONTROL [UNDEF]: 'AUTH_PENDING,timeout 100' (status=1)
tests-openvpn26-1  | 2023-02-24 20:34:17 us=994679 172.19.0.1:60049 SENT CONTROL [UNDEF]: 'INFO_PRE,OPENURL:https://google.de' (status=1)
tests-openvpn26-1  | 2023-02-24 20:34:17 us=994902 172.19.0.1:60049 TLS: Username/Password authentication deferred for username 'joe' 
tests-openvpn26-1  | 2023-02-24 20:34:17 us=995181 172.19.0.1:60049 TLS: move_session: dest=TM_ACTIVE src=TM_INITIAL reinit_src=1
tests-openvpn26-1  | 2023-02-24 20:34:17 us=996166 172.19.0.1:60049 TLS: tls_multi_process: initial untrusted session promoted to semi-trusted
tests-openvpn26-1  | 2023-02-24 20:34:17 us=999612 172.19.0.1:60049 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 2048 bit RSA, signature: RSA-SHA256
tests-openvpn26-1  | 2023-02-24 20:34:17 us=999677 172.19.0.1:60049 [joe] Peer Connection Initiated with [AF_INET]172.19.0.1:60049
tests-openvpn26-1  | 2023-02-24 20:34:19 us=42128 172.19.0.1:60049 PUSH: Received control message: 'PUSH_REQUEST'
```

I think, the line `SENT CONTROL [UNDEF]` is suspicious. 

On OpenVPN 2.5.8, using a management service with management-client-auth, it looks like

```
tests-openvpn-1  | 2023-02-24 20:32:34 172.19.0.1:50418 peer info: IV_VER=2.6.0
tests-openvpn-1  | 2023-02-24 20:32:34 172.19.0.1:50418 peer info: IV_PLAT=win
tests-openvpn-1  | 2023-02-24 20:32:34 172.19.0.1:50418 peer info: IV_TCPNL=1
tests-openvpn-1  | 2023-02-24 20:32:34 172.19.0.1:50418 peer info: IV_MTU=1600
tests-openvpn-1  | 2023-02-24 20:32:34 172.19.0.1:50418 peer info: IV_NCP=2
tests-openvpn-1  | 2023-02-24 20:32:34 172.19.0.1:50418 peer info: IV_CIPHERS=AES-256-GCM:AES-128-GCM
tests-openvpn-1  | 2023-02-24 20:32:34 172.19.0.1:50418 peer info: IV_PROTO=478
tests-openvpn-1  | 2023-02-24 20:32:34 172.19.0.1:50418 peer info: IV_LZO_STUB=1
tests-openvpn-1  | 2023-02-24 20:32:34 172.19.0.1:50418 peer info: IV_COMP_STUB=1
tests-openvpn-1  | 2023-02-24 20:32:34 172.19.0.1:50418 peer info: IV_COMP_STUBv2=1
tests-openvpn-1  | 2023-02-24 20:32:34 172.19.0.1:50418 peer info: IV_GUI_VER=OpenVPN_GUI_11
tests-openvpn-1  | 2023-02-24 20:32:34 172.19.0.1:50418 peer info: IV_SSO=openurl,webauth,crtext
tests-openvpn-1  | 2023-02-24 20:32:34 172.19.0.1:50418 TLS: Username/Password authentication deferred for username 'joe' 
tests-openvpn-1  | 2023-02-24 20:32:34 172.19.0.1:50418 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 2048 bit RSA, signature: RSA-SHA256
tests-openvpn-1  | 2023-02-24 20:32:34 172.19.0.1:50418 [joe] Peer Connection Initiated with [AF_INET]172.19.0.1:50418
tests-openvpn-1  | 2023-02-24 20:32:34 MANAGEMENT: CMD 'client-pending-auth 0 OPEN_URL:https://google.de 600'
tests-openvpn-1  | 2023-02-24 20:32:34 SENT CONTROL [joe]: 'AUTH_PENDING' (status=1)
tests-openvpn-1  | 2023-02-24 20:32:34 SENT CONTROL [joe]: 'INFO_PRE,OPEN_URL:https://google.de' (status=1)
tests-openvpn-1  | 2023-02-24 20:32:35 172.19.0.1:50418 PUSH: Received control message: 'PUSH_REQUEST'
```
`SENT CONTROL [UNDEF]: 'AUTH_PENDING,timeout 100' (status=1)` vs. `SENT CONTROL [joe]: 'AUTH_PENDING' (status=1)`

**Comment by cron2** [comment] 2023-02-24 21:58
Hi,

On Fri, Feb 24, 2023 at 12:49:55PM -0800, Jan-Otto Kröpke wrote:
> **Describe the bug**
> I enabled `auth-user-pass-verify .. via-file` on my server. The program write 3 lines to auth_pending_file and returns exit code 2. The server is advertising authentication deferred, but the client will never get the informations.

How does the client log file look like?

2.6:

> tests-openvpn26-1  | 2023-02-24 20:34:17 us=994581 172.19.0.1:60049 SENT CONTROL [UNDEF]: 'AUTH_PENDING,timeout 100' (status=1)
> tests-openvpn26-1  | 2023-02-24 20:34:17 us=994679 172.19.0.1:60049 SENT CONTROL [UNDEF]: 'INFO_PRE,OPENURL:https://google.de' (status=1)

2.5:

> tests-openvpn-1  | 2023-02-24 20:32:34 SENT CONTROL [joe]: 'AUTH_PENDING' (status=1)
> tests-openvpn-1  | 2023-02-24 20:32:34 SENT CONTROL [joe]: 'INFO_PRE,OPEN_URL:https://google.de' (status=1)

... basically this is the same reply, just with an optional argument,
which the client will parse and either pass on to the management UI
or ignore (if unknown).  These flags are new in 2.6, so "yes it looks
different".

doc/management-notes.txt documents what possible options exist.

I see that you use a 2.6.0 client, so it really should parse and
handle this correctly - but we need the client log to see what is
happening.

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by jkroepke** [comment] 2023-02-24 23:51
For better debugging, I setup a local environment. Server CA may differs, but now I'm able to provide full logs.

Full server logs:

```
2023-02-24 23:48:34 Note: --cipher is not set. OpenVPN versions before 2.5 defaulted to BF-CBC as fallback when cipher negotiation failed in this case. If you need this fallback please add '--data-ciphers-fallback BF-CBC' to your configuration and/or add BF-CBC to --data-ciphers.
2023-02-24 23:48:34 OpenVPN 2.6.0 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD]
2023-02-24 23:48:34 library versions: OpenSSL 3.0.8 7 Feb 2023, LZO 2.10
2023-02-24 23:48:34 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2023-02-24 23:48:34 Using random OpenVPN auth-token server key.
2023-02-24 23:48:34 auth-token secret: Using 256 bit message hash 'SHA256' for HMAC authentication
2023-02-24 23:48:34 TUN/TAP device tun0 opened
2023-02-24 23:48:34 /sbin/ip link set dev tun0 up mtu 1500
2023-02-24 23:48:34 /sbin/ip link set dev tun0 up
2023-02-24 23:48:34 /sbin/ip addr add dev tun0 100.64.0.1/24
2023-02-24 23:48:34 Could not determine IPv4/IPv6 protocol. Using AF_INET
2023-02-24 23:48:34 Socket Buffers: R=[212992->212992] S=[212992->212992]
2023-02-24 23:48:34 UDPv4 link local (bound): [AF_INET][undef]:1194
2023-02-24 23:48:34 UDPv4 link remote: [AF_UNSPEC]
2023-02-24 23:48:34 GID set to nogroup
2023-02-24 23:48:34 UID set to nobody
2023-02-24 23:48:34 MULTI: multi_init called, r=256 v=256
2023-02-24 23:48:34 IFCONFIG POOL IPv4: base=100.64.0.2 size=253
2023-02-24 23:48:34 Initialization Sequence Completed
2023-02-24 23:48:39 172.19.0.1:56665 VERIFY OK: depth=1, CN=Easy-RSA CA
2023-02-24 23:48:39 172.19.0.1:56665 VERIFY OK: depth=0, CN=joe
2023-02-24 23:48:39 172.19.0.1:56665 peer info: IV_VER=2.6.0
2023-02-24 23:48:39 172.19.0.1:56665 peer info: IV_PLAT=win
2023-02-24 23:48:39 172.19.0.1:56665 peer info: IV_TCPNL=1
2023-02-24 23:48:39 172.19.0.1:56665 peer info: IV_MTU=1600
2023-02-24 23:48:39 172.19.0.1:56665 peer info: IV_NCP=2
2023-02-24 23:48:39 172.19.0.1:56665 peer info: IV_CIPHERS=AES-256-GCM:AES-128-GCM
2023-02-24 23:48:39 172.19.0.1:56665 peer info: IV_PROTO=478
2023-02-24 23:48:39 172.19.0.1:56665 peer info: IV_LZO_STUB=1
2023-02-24 23:48:39 172.19.0.1:56665 peer info: IV_COMP_STUB=1
2023-02-24 23:48:39 172.19.0.1:56665 peer info: IV_COMP_STUBv2=1
2023-02-24 23:48:39 172.19.0.1:56665 peer info: IV_GUI_VER=OpenVPN_GUI_11
2023-02-24 23:48:39 172.19.0.1:56665 peer info: IV_SSO=openurl,webauth,crtext
2023-02-24 23:48:40 172.19.0.1:56665 SENT CONTROL [UNDEF]: 'AUTH_PENDING,timeout 35' (status=1)
2023-02-24 23:48:40 172.19.0.1:56665 SENT CONTROL [UNDEF]: 'INFO_PRE,OPEN_URL:https://jkroepke.github.io/openvpn-auth-azure-ad/?code=C2HBRC3P7' (status=1)
2023-02-24 23:48:40 172.19.0.1:56665 TLS: Username/Password authentication deferred for username '' 
2023-02-24 23:48:40 172.19.0.1:56665 TLS: move_session: dest=TM_ACTIVE src=TM_INITIAL reinit_src=1
2023-02-24 23:48:40 172.19.0.1:56665 TLS: tls_multi_process: initial untrusted session promoted to semi-trusted
2023-02-24 23:48:40 172.19.0.1:56665 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 256 bit ED25519, signature: ED25519
2023-02-24 23:48:40 172.19.0.1:56665 [joe@old.adorsys.de] Peer Connection Initiated with [AF_INET]172.19.0.1:56665
2023-02-24 23:48:41 172.19.0.1:56665 PUSH: Received control message: 'PUSH_REQUEST'
2023-02-24 23:48:47 172.19.0.1:56665 PUSH: Received control message: 'PUSH_REQUEST'
2023-02-24 23:48:52 172.19.0.1:56665 PUSH: Received control message: 'PUSH_REQUEST'
2023-02-24 23:48:58 172.19.0.1:56665 PUSH: Received control message: 'PUSH_REQUEST'
2023-02-24 23:49:03 172.19.0.1:56665 PUSH: Received control message: 'PUSH_REQUEST'
2023-02-24 23:49:08 172.19.0.1:56665 Delayed exit in 5 seconds
2023-02-24 23:49:08 172.19.0.1:56665 SENT CONTROL [joe]: 'AUTH_FAILED' (status=1)
2023-02-24 23:49:08 172.19.0.1:56665 PUSH: Received control message: 'PUSH_REQUEST'

```

Full client logs:

```

```

**Comment by schwabe** [comment] 2023-02-25 02:51
This might be a duplicate of https://github.com/OpenVPN/openvpn/issues/256

**Comment by jkroepke** [comment] 2023-02-25 07:55
@schwabe Yeah sounds like an dublicate.

**Comment by mhalden** [comment] 2023-02-27 11:17
This looks like a duplicate to me.

**Comment by jkroepke** [comment] 2023-02-27 15:25
Lets have the hope that newly introduced feature could be fixed in the next minor version.

@schwabe is GitHub is correct place for raise issues OR do I have to open an issue at trac? https://community.openvpn.net/openvpn/

**Comment by cron2** [comment] 2023-03-20 18:05
Hi,

On Fri, Feb 24, 2023 at 12:49:55PM -0800, Jan-Otto Kröpke wrote:
> **Describe the bug**
> I enabled `auth-user-pass-verify .. via-file` on my server. The program write 3 lines to auth_pending_file and returns exit code 2. The server is advertising authentication deferred, but the client will never get the informations.

A patch for #256 has been pushed to openvpn repos today, to be released
as part of 2.6.2 "this week".

It would be good to have confirmation that running an OpenVPN server
with a git checkout "as of today" makes this feature work again
(and in the meantime I'll go and add your sample code to my testbed :-) ).

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by jkroepke** [comment] 2023-03-23 19:57
Hi @cron2 

works with:

```
2023-03-23 19:54:04 OpenVPN 2.6.1 [git:release/2.6/e950ca1b9fca58e9] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] [DCO] built on Mar 23 2023
```

**Comment by cron2** [comment] 2023-03-23 20:24
Hi,

On Thu, Mar 23, 2023 at 12:58:03PM -0700, Jan-Otto Kröpke wrote:
> Hi @cron2 
> 
> works with:
> 
> ```
> 2023-03-23 19:54:04 OpenVPN 2.6.1 [git:release/2.6/e950ca1b9fca58e9] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] [DCO] built on Mar 23 2023
> ```

Thanks for the confirmation.  We'll release 2.6.2 tomorrow (at least
that's the plan), with just two more commits to the release/2.6 branch.

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Closed** 2023-03-27 18:48 UTC
