### ISSUE TITLE
[Mac] OpenVPN Connect 3.3.5 - no internet after disconnect

### ISSUE THREAD

**Issue by apivovarov** [OpenVPN/openvpn#202] opened 2022-12-20 20:16 UTC
Tested on Mac OS 12.6.1 and Mac OS 13.1
OpenVPN Connect 3.3.5 

Internet does not work after VPN Disconnect.
Workaround - disconnect and connect to Wi-Fi

ping after VPN disconnect
```
alex@MacBook-Air ~ % ping 8.8.4.4            

PING 8.8.4.4 (8.8.4.4): 56 data bytes
ping: sendto: No route to host
ping: sendto: No route to host
Request timeout for icmp_seq 0
ping: sendto: No route to host
Request timeout for icmp_seq 1
ping: sendto: No route to host
Request timeout for icmp_seq 2
ping: sendto: No route to host
Request timeout for icmp_seq 3
ping: sendto: No route to host
Request timeout for icmp_seq 4
```

**Comment by schwabe** [comment] 2022-12-20 21:16
You are reporting an issue for OpenVPN Connect, the commerical offering of OpenVPN Inc. The OpenVPN Connect team does not want issues reported via Github but rather report them via https://support.openvpn.net/. Please use that website if you want to report an issue with OpenVPN Connect or have any other issue with that application.

Also reporting issues multiple times is  not helpful either (duplicate of https://github.com/OpenVPN/openvpn3/issues/252)

**Closed by schwabe** 2022-12-20 21:16 UTC
