### ISSUE TITLE
OpenVPN-GUI v2.6.1 command line "disconnect_all" bug

### ISSUE THREAD

**Issue by loxia01** [OpenVPN/openvpn#274] opened 2023-03-11 08:16 UTC
**Describe the bug**
When running the `openvpn-gui.exe` command line option `--command disconnect_all`, in addition to terminate all connections, the OpenVPN-GUI taskbar icon completely disappears from the taskbar. It is not be found in the hidden icon popup either.
The program is till running. To get the taskbar icon back again, I have to stop and restart the application.

**To Reproduce**
Run  `openvpn-gui.exe --command disconnect_all` from command line. It does not matter if you have an active connection or not. 

**Expected behavior**
Expected behavior (and the behavior before installing v2.6.1) would be to terminate all connections but leave the taskbar icon visible on the taskbar or in the overflow (hidden) popup.

**Version information (please complete the following information):**
 - OS: Windows 10 22H2
 - OpenVPN version: 2.6.1

**Comment by selvanair** [comment] 2023-03-11 10:41
Duplicate of https://github.com/OpenVPN/openvpn-gui/issues/607
A fix is here: https://github.com/OpenVPN/openvpn-gui/pull/608 -- pending review

@loxia01 If you want test the fix, use openvpn-gui.exe from GHA build of the above PR -- https://github.com/OpenVPN/openvpn-gui/actions/runs/4381698945#artifacts

**Closed** 2023-03-11 19:28 UTC
