### ISSUE TITLE
After the openvpn client is started, the public ip address of the server changes and the connection fails

### ISSUE THREAD

**Issue by LmSAMA** [OpenVPN/openvpn#570] opened 2024-07-04 06:30 UTC
hello,I want to ask, after I start the openvpn client on ecs, I cannot access my instance through the ecs public ip address, can only restart the ecs to terminate the openvpn client program, how should I configure client.ovpn to solve this problem?

**Comment by ordex** [comment] 2024-09-25 13:16
assuming you're running linux on your client, you need policy routing to properly access its public IP.
Otherwise you could access it via VPN IP from the server.

Please note that this is not a bug, therefore I Am going to close this ticket.
Feel free to open a discussion or join IRC or the forum to talk more about your problem

**Closed by ordex** 2024-09-25 13:16 UTC
