### ISSUE TITLE
OpenVPN 2.6 fails Azure VPN Gateway connection on Linux

### ISSUE THREAD

**Issue by UnoSD** [OpenVPN/openvpn#289] opened 2023-03-19 11:32 UTC
**Describe the bug**
After upgrading from `OpenVPN 2.5.8` to `OpenVPN 2.6.x` (tested 2.6.0 and 2.6.1) the client does not connect P2S to Azure VPN Gateway

**To Reproduce**
Upgrade to 2.6.x and try and connect

**Expected behavior**
Connection to estabilish

**Version information (please complete the following information):**
 - OS: Arch Linux
 - OpenVPN version: 2.6.x

**Additional context**

OpenVPN log (looping those messages every restart):

```
2023-01-30 23:04:16 Restart pause, 8 second(s)
2023-01-30 23:04:24 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
2023-01-30 23:04:24 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
2023-01-30 23:04:24 TCP/UDP: Preserving recently used remote address: [AF_INET]<REDACTED>:443
2023-01-30 23:04:24 Socket Buffers: R=[131072->131072] S=[16384->16384]
2023-01-30 23:04:24 Attempting to establish TCP connection with [AF_INET]<REDACTED>:443
2023-01-30 23:04:24 TCP connection established with [AF_INET]<REDACTED>:443
2023-01-30 23:04:24 TCPv4_CLIENT link local: (not bound)
2023-01-30 23:04:24 TCPv4_CLIENT link remote: [AF_INET]<REDACTED>:443
2023-01-30 23:04:24 TLS: Initial packet from [AF_INET]<REDACTED>:443, sid=56431967 caa560cd
2023-01-30 23:04:24 Connection reset, restarting [0]
2023-01-30 23:04:24 SIGUSR1[soft,connection-reset] received, process restarting
2023-01-30 23:04:24 Restart pause, 16 second(s)
2023-01-30 23:04:26 SIGINT[hard,init_instance] received, process exiting
```

OpenVPN file:

```
client
remote <REDACTED> 443
verify-x509-name '<REDACTED>' name
remote-cert-tls server

dev tun
proto tcp
resolv-retry infinite
nobind

auth SHA256
cipher AES-256-GCM
persist-key
persist-tun

tls-timeout 30
tls-version-min 1.2
key-direction 1

log openvpn.log
verb 3

# P2S CA root certificate
<ca>
-----BEGIN CERTIFICATE-----
<REDACTED>
-----END CERTIFICATE-----
</ca>

# Pre Shared Key
<tls-auth>
-----BEGIN OpenVPN Static key V1-----
<REDACTED>
-----END OpenVPN Static key V1-----
</tls-auth>

# P2S client certificate
# Please fill this field with a PEM formatted client certificate
# Alternatively, configure 'cert PATH_TO_CLIENT_CERT' to use input from a PEM certificate file.
<cert>
-----BEGIN CERTIFICATE-----
<REDACTED>
-----END CERTIFICATE-----
</cert>

# P2S client certificate private key
# Please fill this field with a PEM formatted private key of the client certificate.
# Alternatively, configure 'key PATH_TO_CLIENT_KEY' to use input from a PEM key file.
<key>
-----BEGIN RSA PRIVATE KEY-----
<REDACTED>
-----END RSA PRIVATE KEY-----
</key>
```

Azure VPN gateway generated with IaC from settings here: https://github.com/UnoSD/Pulumi.FSharp.Extensions.Examples/blob/main/AzureNative/LinuxP2SOpenVPN/Program.fs
https://github.com/UnoSD/Pulumi.FSharp.Extensions.Examples

**Comment by schwabe** [comment] 2023-03-19 11:49
Duplicate of #236

**Closed by schwabe** 2023-03-19 11:49 UTC
