### ISSUE TITLE
2.6.1 crash when tls-crypt-v2 is used

### ISSUE THREAD

**Issue by totaldefence** [OpenVPN/openvpn#292] opened 2023-03-20 11:22 UTC
After upgrading existing client and server to 2.6.1, where both client and server use tls-crypt-v2, the following error results:

"read UDPv4 [ECONNREFUSED]: Connection refused (fd=3,code=111)"

Workarounds resulting in a successful connection:
1). Disable use of tls-crypt-v2 on client and server
or
2). Downgrade client to 2.6.0 while leaving server at 2.6.1

Could this error have something to do with the "Dynamic TLS Crypt: When both peers are OpenVPN 2.6.1+, OpenVPN will dynamically create a tls-crypt key that is used for renegotiation"?

----- stdout -----

OpenVPN 2.6.1 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] [DCO]
........ library versions: OpenSSL 3.0.2 15 Mar 2022, LZO 2.10
........ TCP/UDP: Preserving recently used remote address: [AF_INET]192.168.1.1:1194
........ UDPv4 link local: (not bound)
........ UDPv4 link remote: [AF_INET]192.168.1.1:1194
........ TLS: Initial packet from [AF_INET]192.168.1.1:1194, sid=1a70d6b2 d2f89442
........ VERIFY OK: ...
........ VERIFY KU OK
........ Validating certificate extended key usage
........ ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
........ VERIFY EKU OK
........ VERIFY X509NAME OK: ...
........ VERIFY OK: depth=0, ...
........ Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, ...
........ [Server1] Peer Connection Initiated with [AF_INET]192.168.1.1:1194
........ TLS: move_session: dest=TM_ACTIVE src=TM_INITIAL reinit_src=1
........ TLS: tls_multi_process: initial untrusted session promoted to trusted
........ SENT CONTROL [Server1]: 'PUSH_REQUEST' (status=1)
........ read UDPv4 [ECONNREFUSED]: Connection refused (fd=3,code=111)
........ read UDPv4 [ECONNREFUSED]: Connection refused (fd=3,code=111)

**Comment by cron2** [comment] 2023-03-20 11:30
Hi,

On Mon, Mar 20, 2023 at 04:22:43AM -0700, Ari Hämäläinen wrote:
> After upgrading existing client and server to 2.6.1, where both client and server use tls-crypt-v2, the following error results:
> 
> "read UDPv4 [ECONNREFUSED]: Connection refused (fd=3,code=111)"
> 
> Workarounds resulting in a successful connection:
> 1). Disable use of tls-crypt-v2 on client and server
> or
> 2). Downgrade client to 2.6.0 while leaving server at 2.6.1
> 
> Could this error have something to do with the "Dynamic TLS Crypt: When both peers are OpenVPN 2.6.1+, OpenVPN will dynamically create a tls-crypt key that is used for renegotiation"?

The server log should show an ASSERT() error in this case.  This is a
known bug in some 2.6.1 to 2.6.1 constallations, and a bugfix has been
committed already and will be released as part of 2.6.2 this week:

commit ae6068842854278de70264218516b0e4fcdfc6d9
Author: Arne Schwabe ***@***.***>
Date:   Thu Mar 9 13:00:31 2023 +0100

    Ensure n = 2 is set in key2 struct in tls_crypt_v2_unwrap_client_key
    
    The ASSERT in xor_key2 assumes that all methods that load a key2 struct
    correctly set n=2. However, tls_crypt_v2_unwrap_client_key loads a key
    without setting n = 2, triggering the assert.
    
    Github: Closes and reported in OpenVPN/openvpn#272

(so this is likely a duplicate of #272)

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by totaldefence** [comment] 2023-03-25 17:16
> 2.6.2 has been released. Please test if this fixes your crashes.

Confirmed. 2.6.2 fixes this issue.

**Closed** 2023-03-25 17:17 UTC
