### ISSUE TITLE
The visited host is unable to obtain the client IP of OpenVPN, only the IP of the OpenVPN server will be obtained

### ISSUE THREAD

**Issue by 17096835560** [OpenVPN/openvpn#553] opened 2024-05-16 03:13 UTC

**Comment by ordex** [comment] 2024-05-16 07:27
that's because the host you are visiting it outside of the VPN and your server is doing NAT.
This is expected unless you assign public IPs to your clients (unlikely to happen).

I am closing this ticket as this is not a bug.

If you need to further discuss, please use the mailing list, the IRC channel or the forum.

**Closed by ordex** 2024-05-16 07:27 UTC
