### ISSUE TITLE
Build error when building with MSVC from release tarball

### ISSUE THREAD

**Issue by m14ebrskull5** [OpenVPN/openvpn#344] opened 2023-05-26 13:38 UTC
when I run msbuild in root dir, follow errors reported
```
NMAKE : fatal error U1073: don't know how to make 'version.m4.in' [E:\tmp\openvpn-2.6.4\build\msvc\msvc-generate\msvc-g
enerate.vcxproj]
  Stop.
C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(45,5): error
 MSB3073: 命令“nmake -f Makefile.mak all”已退出，代码为 2。 [E:\tmp\openvpn-2.6.4\build\msvc\msvc-generate\msvc-generate.vcxproj]
```
my vs version is MSBuild version 17.7.0-preview-23226-04+0dbc421ea for .NET Framework

**Comment by m14ebrskull5** [comment] 2023-05-27 08:55
It is wierd that in v.2.6.4 release, there is no file named version.m4.in  _\build\msvc\msvc-generate_.
however it actualy exists in master branch, I think it is the problem

**Comment by cron2** [comment] 2023-05-27 09:04
Are you trying to build from a tarball?  That might be the cause... the "release/2.6" git branch does have the `version.m4.in` file, but it seems the packaging rules are not right, so it's not ending in the tarball.

(You're the first to try building on Windows from a tarball, so nobody has noticed this before - everybody else either uses the release binaries, or pulls the git tree)

@lstipakov, @flichtenheld should be an easy fix for 2.6.5, no?

**Comment by flichtenheld** [comment] 2023-05-27 09:55
Patch on the list.

**Comment by flichtenheld** [comment] 2023-05-27 09:57
Note to self: before closing this issue, actually test that MSVC build from tarball works now.

**Comment by cron2** [comment] 2023-05-27 10:39
> Patch on the list.
That was faster than expected!

Will merge & reopen the issue after GH auto-closes it.

**Comment by cron2** [comment] 2023-05-27 16:50
reopening, as @flichtenheld wants to close this after doing a MSVC-from-tarball testbuild.

**Comment by flichtenheld** [comment] 2023-06-14 10:24
So turns out there where several additional files missing. Patches are on the list. For 2.6.6 we might actually have a release tarball you can build directly with MSVC. Until then you will need to use a git checkout.

**Closed** 2023-06-21 11:43 UTC
Labels: bug, Windows
