### ISSUE TITLE
Installing OpenVPN 2.6.0 (64-bit) on a fully patched Win 10 computer causes it to become non-bootable

### ISSUE THREAD

**Issue by OhYesIndeed** [OpenVPN/openvpn#241] opened 2023-02-07 13:59 UTC
Very serious bug report incoming.

Short version: Installing OpenVPN client version 2.6.0 (64-bit) causes a fully patched Windows 10 Pro machine to become non-bootable.
The client was downloaded from: https://openvpn.net/community-downloads/

Long version:

The machine in question is a Dell Vostro 3500 series notebook (relatively new, 11th gen Intel CPU). I have run into the similar problem in four consecutive installs/scenarios.

1: The computer was running the original OS from the factory. I fully updated the computer OS, Dell updates and other software before handing it over to the employee and as the last procedure updated OpenVPN client to 2.6.0. I got a message from the on-site person that the computer refuses to boot: DELL logo is on the screen, the circle which indicates the OS is trying to boot is moving around but nothing is happening. (In one case I left it running overnight, 10+ hours in total.) At this point I had no reason to doubt OpenVPN client as the source of the problems.

2: The on-site person made a factory reset from the recovery image on the drive. I fully updated the computer again, installed all other required software and finally installed OpenVPN 2.6.0. The computer immediately ended up in the same non-bootable state. At this point my doubt was a faulty OS recovery image from the manufacturer (I have run into a similar scenario couple of times before).

3: The on-site person generated a new Win 10 install USB disk from the Microsoft Media Creation Tool, wiped the entire disk and installed a fresh copy of Win 10 Pro. I updated the OS, installed all other software and Dell updates - and made several restarts in the process as with the previous install scenarios - and last but not least, I installed OpenVPN 2.6.0. Immediately after the next restart the computer was not able to boot.

4: The on-site person made an OS recovery (since Win 10 said it was unable to boot and offered diagnostic options). Now I fully updated the Win 10 install and *before installing any other software*, installed OpenVPN 2.6.0, restarted the computer and again the computer was in a non-bootable state. This time we waited 45 min for the computer to boot up but it is clear we ran into the same issue.

I am investigating the issue on a virtual machine, I will let you know how it goes.

Meanwhile, if I can provide any other information that could be useful in solving this case, please let me know.

**Comment by lstipakov** [comment] 2023-02-07 14:03
This is already fixed in version I004, but our web team a bit slow in updating the main website. You can download the latest version from https://community.openvpn.net/openvpn/wiki/Downloads

Direct download link: https://swupdate.openvpn.org/community/releases/OpenVPN-2.6.0-I004-amd64.msi

**Comment by cron2** [comment] 2023-02-07 14:05
Hi,

On Tue, Feb 07, 2023 at 06:00:08AM -0800, OhYesIndeed wrote:
> Very serious bug report incoming.
> 
> Short version: Installing OpenVPN client version 2.6.0 (64-bit) causes a fully patched Windows 10 Pro machine to become non-bootable.
> The client was downloaded from: https://openvpn.net/community-downloads/

This is known, and a new I004 installer has been provided already :-)

https://swupdate.openvpn.org/community/releases/OpenVPN-2.6.0-I004-amd64.msi

(the download page does not list I004 yet, as there is web designers
in the way - apologies for that)

See https://github.com/OpenVPN/ovpn-dco-win/issues/24 for more details.

[..]
> I am investigating the issue on a virtual machine, I will let you know how it goes.

This seems to be a weird interaction with Dell, so VMs and other brands
do not show the effect.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by OhYesIndeed** [comment] 2023-02-07 14:07
One would say that the computer being not able to boot due to a faulty sofware release is an **extremely critical issue** and would require **immediate attention** in replacing the faulty release on the website's download section?

I'm sorry if I sound somewhat bitter. That's because I am.

**Comment by cron2** [comment] 2023-02-07 14:10
Hi,

On Tue, Feb 07, 2023 at 06:08:04AM -0800, OhYesIndeed wrote:
> One would say that the computer being not able to boot due to a faulty sofware release is an **extremely critical issue** and would require **immediate attention** in replacing the faulty release on the website's download section?

One could say that.  OTOH, please do complain to Dell about it as well,
because it's something in their preinstallations.

> I'm sorry if I sound somewhat bitter. That's because I am. 

Relax and get a nice cup of hot beverage of your choice.  We are working
on it, but employment laws in Europe do not permit more drastic measures.

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by OhYesIndeed** [comment] 2023-02-07 14:13
By the way, it is not an issue only with Dell pre-installs. As I mentioned, it also happened with a clean install done with a MS installer. If it is happening only on Dell machines, it has to be either hardware, firmware or BIOS level issue.

As for complaining to Dell... extensive experience in that regard allows me to label this activity completely futile. Sort of like yelling at the Sun for being too hot, only less enjoyable.

**Comment by cron2** [comment] 2023-02-07 14:16
It's something Dell machines pull from windows update, see the referenced issue.  After a clean install, installing openvpn+dco and booting *once* works fine.  Then the machine downloads and installs lots of stuff, after which booting fails.

But we do not need to further discuss this - I agree with you that the problem is extremely annoying, and we apologize for the pains it caused.  Installer and DCO driver were tested on a number of different installers over the last half year, and nothing triggered this.

Also, we apologize for the slow update process on the openvpn.net web site - this *is* being worked on, but there is some tension between the OpenVPN Community work and the sponsoring company OpenVPN Inc on "who gets to update the web site, and how often".  Resolving this with civilized methods takes time.

**Closed by cron2** 2023-02-07 14:16 UTC
Labels: bug, DCO, Windows
