### ISSUE TITLE
tls-crypt-v2 - Assertion failed at tls_crypt.c:83

### ISSUE THREAD

**Issue by tranzitwww** [OpenVPN/openvpn#275] opened 2023-03-13 21:13 UTC
**Describe the bug**
Recently I've updated the server and clients to 2.6.1 and I've discovered the new option "tls-crypt-v2" in the documentation and I decided to migrate from "tls-crypt" (v1) to that one, but it didn't worked as expected.

1. I've generated the new keys for both server and clients (on the server)
```
openvpn --genkey tls-crypt-v2-server v2crypt-server.key
openvpn --tls-crypt-v2 v2crypt-server.key --genkey tls-crypt-v2-client v2crypt-client-1.key
openvpn --tls-crypt-v2 v2crypt-server.key --genkey tls-crypt-v2-client v2crypt-client-2.key
openvpn --tls-crypt-v2 v2crypt-server.key --genkey tls-crypt-v2-client v2crypt-client-3.key
```
2. I've updated the configs to use the new keys (I didn't used both tls-crypt and tls-crypt-v2 ! Just tls-crypt-v2)
This is the only line changed in the configs
```
Server:
tls-crypt-v2 <absolute_path>/v2crypt-server.key

Client:
tls-crypt-v2 <absolute_path>\\v2crypt-client-1.key
```
4. Restart the OpenVPN service (no errors in the log during restart)
5. Connect the client while checking the server logs
```
Control Channel: using tls-crypt-v2 key
Connection Attempt Control Channel: using tls-crypt-v2 key
1.2.3.4:52349 Control Channel: using tls-crypt-v2 key
1.2.3.4:52349 VERIFY OK: depth=1, CN=Root CA
1.2.3.4:52349 VERIFY KU OK
1.2.3.4:52349 Validating certificate extended key usage
1.2.3.4:52349 ++ Certificate has EKU (str) TLS Web Client Authentication, expects TLS Web Client Authentication
1.2.3.4:52349 VERIFY EKU OK
1.2.3.4:52349 VERIFY OK: depth=0, CN=Client1
1.2.3.4:52349 peer info: IV_VER=2.6.1
1.2.3.4:52349 peer info: IV_PLAT=win
1.2.3.4:52349 peer info: IV_TCPNL=1
1.2.3.4:52349 peer info: IV_MTU=1600
1.2.3.4:52349 peer info: IV_CIPHERS=AES-256-GCM
1.2.3.4:52349 peer info: IV_PROTO=990
1.2.3.4:52349 peer info: IV_LZO_STUB=1
1.2.3.4:52349 peer info: IV_COMP_STUB=1
1.2.3.4:52349 peer info: IV_COMP_STUBv2=1
1.2.3.4:52349 peer info: IV_HWADDR=12:34:56:78:9a:bc
1.2.3.4:52349 peer info: IV_SSL=OpenSSL_3.0.8_7_Feb_2023
1.2.3.4:52349 peer info: IV_PLAT_VER=6.1,_amd64_executable
1.2.3.4:52349 TLS: move_session: dest=TM_ACTIVE src=TM_INITIAL reinit_src=1
1.2.3.4:52349 TLS: tls_multi_process: initial untrusted session promoted to trusted
1.2.3.4:52349 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 4096 bit RSA, signature: RSA-SHA256
1.2.3.4:52349 [Client1] Peer Connection Initiated with [AF_INET]1.2.3.4:52349
Client1/1.2.3.4:52349 MULTI_sva: pool returned IPv4=10.3.122.250, IPv6=(Not enabled)
Client1/1.2.3.4:52349 Assertion failed at tls_crypt.c:83 (key->n == 2 && other->n == 2)
Client1/1.2.3.4:52349 Exiting due to fatal error
Client1/1.2.3.4:52349 Closing TUN/TAP interface

```

It fails with this message: **Assertion failed at tls_crypt.c:83 (key->n == 2 && other->n == 2)**
If I switch back to tls-crypt with v1 keys it works without any problems.

**Version information:**
Server
 - OS: CentOS 7
 - OpenVPN version: 2.6.1

Client
 - OS: Windows 10
 - OpenVPN version: 2.6.1

**Additional context**

The server was build using this:
```
./configure --enable-static --enable-iproute2 --with-crypto-library=openssl \
OPENSSL_LIBS="-L/kits/openssl-3.0.8/ -lssl -lcrypto" OPENSSL_CFLAGS="-I/kits/openssl-3.0.8/include/" \
LZO_LIBS="-L/kits/lzo-2.10/ -llzo2" LZO_CFLAGS="-I/kits/lzo-2.10/include/" \
LZ4_LIBS="-L/kits/lz4-1.9.4/lib/ -llz4" LZ4_CFLAGS="-I/kits/lz4-1.9.4/programs/"

make
make install
```

**Comment by ordex** [comment] 2023-03-13 21:19
Thanks for the report! However this is a duplicate of #272

**Closed by ordex** 2023-03-13 21:19 UTC

**Comment by cron2** [comment] 2023-03-13 21:21
Hi,

On Mon, Mar 13, 2023 at 02:14:14PM -0700, tranzitwww wrote:
> **Describe the bug**
> Recently I've updated the server and clients to 2.6.1 and I've discovered the new option "tls-crypt-v2" in the documentation and I decided to migrate from "tls-crypt" (v1) to that one, but it didn't worked as expected.
[..]
> Client1/1.2.3.4:52349 Assertion failed at tls_crypt.c:83 (key->n == 2 && other->n == 2)

Unfortunately this is a known bug newly introduced in 2.6.1 - a fix has
already been committed (see GH issue OpenVPN/openvpn#272), and will be part
of 2.6.2 to be released "very soon".

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by tranzitwww** [comment] 2023-03-13 21:37
Thank you so much for your quick response.
I confirm that the [patch code ](https://patchwork.openvpn.net/project/openvpn2/patch/20230309120031.3780130-1-arne@rfc2549.org/) works. I've just updated the server code :)

**Comment by ordex** [comment] 2023-03-13 21:40
Thanks for your feedback! @schwabe we got one more confirmation :)
