### ISSUE TITLE
Cannot connect to Mikrotik's OVPN server with versions 2.6.0-2.6.5

### ISSUE THREAD

**Issue by dmitriyteteruk** [OpenVPN/openvpn#372] opened 2023-07-21 10:25 UTC
Hi! I cannot connect to OVPN server on Mikrotik using OVPN Client versions 2.6.0-2.6.5. OS is Windows 11 x64.
As workaround I am using 2.5.9 community version now, but at the same time Client openvpn-connect-3.4.0.3121_signed_(tap_dco) works fine.

Connection process stuck with below message in log on version 2.6.0-2.6.5:
```
Fri Jul 21 13:06:34 2023 VERIFY KU OK
Fri Jul 21 13:06:34 2023 NOTE: --mute triggered...
Fri Jul 21 13:07:33 2023 4 variation(s) on previous 10 message(s) suppressed by --mute
Fri Jul 21 13:07:33 2023 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Fri Jul 21 13:07:33 2023 TLS Error: TLS handshake failed
```

**Comment by schwabe** [comment] 2023-07-26 09:44
This is probably also a duplicate of #253

**Comment by flichtenheld** [comment] 2024-03-15 16:26
Closing as duplicate

**Closed by flichtenheld** 2024-03-15 16:26 UTC
