### ISSUE TITLE
OpenVPN version 2.6.12 is not able to connect to openvpn client v3 in udp mode.

### ISSUE THREAD

**Issue by ChauhanPriyanka** [OpenVPN/openvpn#653] opened 2024-12-11 13:50 UTC
Hi team, 

I have upgraded OpenVPN server from 2.5.6 to 2.6.12.
Post openvpn server upgrade, Android clients version 2.4 version (old), is able to connect to openvpn server 2.6.12.
However the IOS client (_3.0, last commit picked in June 2014 - https://github.com/OpenVPN/openvpn3/commit/708c19d20ca16ebba6c1d3c56a151f89c87c83b4_ ) is not able to connect to open vpn server anymore. I figured out there is cipher issue i.e. no common cipher between server and client. On adding `ncp-ciphers AES-256-GCM:AES-256-CBC` option in server config I was able to connect IOS client with TCP. 

However IOS client is still not connecting in UDP. I tried to adjust `tun-mtu` `fragment` and` mssfix` paramter, vpn is connected rarely like 1 out of 100 times. It did not connect with the same parameter next time,

Can you please help me adjust the parameters, so the connection in UDP mode starts working. Or is there any option in UDP mode to make the vpn server backward compatible. I tried adding `compat-mode 2.4.0` but it did not fix the issue
Below are the configuration details 

server.conf

```
dev tun
dev-node VPNT
topology subnet
port 8114
proto udp
persist-key 
persist-tun 
server  10.1.0.224 255.255.255.224
keepalive 60 300
plugin "C:\\tls-plugin.dll"
log-append "C:\\ProgramData\\VPN\\log4c.conf"
status "C:\\ProgramData\\VPN\\vpn-status.log" 47
ca "C:\\ProgramData\\VPN\\ca.crt"
cert "C:\\ProgramData\\VPN\\server.crt"
key "C:\\ProgramData\\VPN\\server.key"
tls-auth "C:\\ProgramData\\VPN\\TA.key"
auth SHA256
dh "C:\\ProgramData\\VPN\\dh2048.pem"
push "redirect-gateway def1 bypass-dhcp "
push "dhcp-option DNS 8.8.8.8"
compress migrate
management 127.0.0.1 56834
tls-timeout 3
cipher AES-256-CBC
ncp-ciphers AES-256-GCM:AES-256-CBC
tls-version-min 1.2
tls-cipher TLS-DHE-RSA-WITH-AES-256-CBC-SHA256


#BEGIN_CUSTOM_SETTINGS

verb 6

#END_CUSTOM_SETTINGS

```

client.conf
```

client
server-poll-timeout 4
nobind
remote vpn.testserver.com 8114 udp
dev tun
comp-lzo yes
inactive 300 600
verb 9
persist-key
persist-tun
cipher AES-256-CBC
tls-version-min 1.2
auth SHA256
<tls-auth>
-----BEGIN Static key V1-----
-----END Static key V1-----
</tls-auth>
<ca>
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN RSA PRIVATE KEY-----
-----END RSA PRIVATE KEY-----
</key>
```

server failure logs
```
INFO      -  us=126813 Connection Attempt MULTI: multi_create_instance called
INFO      -  us=143839 20.163.82.254:44443 Re-using SSL/TLS context
INFO      -  us=159135 20.163.82.254:44443 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
INFO      -  us=169353 20.163.82.254:44443 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
INFO      -  us=178972 20.163.82.254:44443 Control Channel MTU parms [ mss_fix:0 max_frag:0 tun_mtu:1250 tun_max_mtu:0 headroom:126 payload:1600 tailroom:126 ET:0 ]
INFO      -  us=188714 20.163.82.254:44443 Data Channel MTU parms [ mss_fix:0 max_frag:0 tun_mtu:1500 tun_max_mtu:1600 headroom:136 payload:1768 tailroom:562 ET:0 ]
INFO      -  us=197991 20.163.82.254:44443 UDPv6 READ [414] from [AF_INET6]::ffff:20.163.82.254:44443: P_CONTROL_V1 kid=0 pid=[ #3 ] [ ] pid=2 DATA len=360
ERROR     -  us=207319 20.163.82.254:44443 TLS Error: Unroutable control packet received from [AF_INET6]::ffff:20.163.82.254:44443 (si=3 op=P_CONTROL_V1)
INFO      -  us=216408 20.163.82.254:44443 LINK packet from [248.127.0.0/234] destined for [UNKNOWN]
INFO      -  us=225025 20.163.82.254:44443 UDPv6 READ [62] from [AF_INET6]::ffff:20.163.82.254:44443: P_ACK_V1 kid=0 pid=[ #4 ] [ 0 ] DATA len=0
ERROR     -  us=234432 20.163.82.254:44443 TLS Error: Unroutable control packet received from [AF_INET6]::ffff:20.163.82.254:44443 (si=3 op=P_ACK_V1)
INFO      -  us=243417 20.163.82.254:44443 LINK packet from [248.127.0.0/234] destined for [UNKNOWN]
INFO      -  us=107467 20.163.82.254:44443 UDPv6 READ [66] from [AF_INET6]::ffff:20.163.82.254:44443: P_CONTROL_HARD_RESET_CLIENT_V2 kid=0 pid=[ #2 ] [ 0 ] pid=1 DATA len=0
INFO      -  us=125086 20.163.82.254:44443 TLS: Initial packet from [AF_INET6]::ffff:20.163.82.254:44443, sid=2575aee9 aa84ea47
ERROR     -  us=136820 20.163.82.254:44443 TLS Error: reading acknowledgement record from packet
INFO      -  us=146739 20.163.82.254:44443 LINK packet from [248.127.0.0/234] destined for [UNKNOWN]
INFO      -  us=156332 20.163.82.254:44443 UDPv6 WRITE [54] to [AF_INET6]::ffff:20.163.82.254:44443: P_CONTROL_HARD_RESET_SERVER_V2 kid=0 pid=[ #1 ] [ ] pid=0 DATA len=0
INFO      -  us=165324 20.163.82.254:44443 UDPv6 READ [414] from [AF_INET6]::ffff:20.163.82.254:44443: P_CONTROL_V1 kid=0 pid=[ #3 ] [ ] pid=2 DATA len=360
INFO      -  us=174284 20.163.82.254:44443 LINK packet from [248.127.0.0/234] destined for [UNKNOWN]
INFO      -  us=182455 20.163.82.254:44443 UDPv6 WRITE [62] to [AF_INET6]::ffff:20.163.82.254:44443: P_ACK_V1 kid=0 pid=[ #2 ] [ 2 ] DATA len=0
INFO      - us=111245 20.163.82.254:44443 UDPv6 READ [66] from [AF_INET6]::ffff:20.163.82.254:44443: P_CONTROL_HARD_RESET_CLIENT_V2 kid=0 pid=[ #2 ] [ 0 ] pid=1 DATA len=0
INFO      - us=126077 20.163.82.254:44443 PID_ERR replay-window backtrack occurred [1] [TLS_WRAP-0] [22_] 1729584337:3 1729584337:2 t=1729584342[0] r=[-2,64,15,1,1] sl=[61,3,64,528]
INFO      - us=140830 20.163.82.254:44443 PID_ERR replay [1] [TLS_WRAP-0] [22_] 1729584337:3 1729584337:2 t=1729584342[0] r=[-2,64,15,1,1] sl=[61,3,64,528]
ERROR     - us=151114 20.163.82.254:44443 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #2 / time = (1729584337) 03:05:37 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
ERROR     - us=161576 20.163.82.254:44443 TLS Error: incoming packet authentication failed from [AF_INET6]::ffff:20.163.82.254:44443
INFO      - us=170483 20.163.82.254:44443 LINK packet from [248.127.0.0/234] destined for [UNKNOWN]
INFO      - us=179701 20.163.82.254:44443 UDPv6 READ [414] from [AF_INET6]::ffff:20.163.82.254:44443: P_CONTROL_V1 kid=0 pid=[ #3 ] [ ] pid=2 DATA len=360
INFO      - us=189622 20.163.82.254:44443 PID_ERR replay [0] [TLS_WRAP-0] [22_] 1729584337:3 1729584337:3 t=1729584342[0] r=[-2,64,15,1,1] sl=[61,3,64,528]
ERROR     -  us=302573 20.163.82.254:44443 TLS Error: incoming packet authentication failed from [AF_INET6]::ffff:20.163.82.254:44443
INFO      -  us=319106 20.163.82.254:44443 LINK packet from [248.127.0.0/234] destined for [UNKNOWN]
ERROR     -  us=757727 20.163.82.254:44443 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
ERROR     -  us=778504 20.163.82.254:44443 TLS Error: TLS handshake failed
INFO      - us=796896 20.163.82.254:44443 SIGUSR1[soft,tls-error] received, client-instance restarting
```

client failure logs
```
[MVPNProviderManagerModel init][30654]|57<Info>: Register notification when app will enter foreground 
|[MVPNProviderManagerModel loadManagers][30654]|106<Info>: Start load all provider managers
[MVPNProviderManagerModel loadManagers]_block_invoke[30654]|112<Info>: Load 1 provider managers successfully
[MVPNProviderManagerModel selectedManager][30654]|391<Info>: Get enabled provider manager index(0), total profiles count(1)
[MVPNProviderManagerModel start:][30654]|473<Info>: Start vpn: VPN ios 
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[30654]|631<Info>: No response from extention
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[30654]|543<Info>: VPN updated status: Connecting, UI delegate = <MVPNMainViewController: 0x1007093f0>
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[30654]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[30654]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[30654]|631<Info>: No response from extention
|-[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[30654]|631<Info>: No response from extention
|-[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[30654]|631<Info>: No response from extention
[MVPNProviderManagerModel appDidEnterBackground:][30654]|94<Info>: App did enter background
[MVPNProviderManagerModel appWillEnterForeground:][30654]|85<Info>: App will enter foreground
[MVPNProviderManagerModel loadManagers][30654]|106<Info>: Start load all provider managers
[MVPNProviderManagerModel loadManagers]_block_invoke[30654]|112<Info>: Load 1 provider managers successfully
[MVPNProviderManagerModel appDidEnterBackground:][30654]|94<Info>: App did enter background
[MVPNProviderManagerModel init][34289]|57<Info>: Register notification when app will enter foreground 
[MVPNProviderManagerModel loadManagers][34289]|106<Info>: Start load all provider managers
[MVPNProviderManagerModel loadManagers]_block_invoke[34289]|112<Info>: Load 1 provider managers successfully
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel loadManagers][34289]|106<Info>: Start load all provider managers
[MVPNProviderManagerModel loadManagers]_block_invoke[34289]|112<Info>: Load 1 provider managers successfully
[MVPNProviderManagerModel stopVPN][34289]|497<Info>: Stop vpn: VPN ios 
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|548<Info>: VPN updated status: Disconnecting, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|548<Info>: VPN updated status: Disconnecting, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|553<Info>: VPN updated status: Disconnected, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|553<Info>: VPN updated status: Disconnected, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel start:][34289]|473<Info>: Start vpn: VPN ios 
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|543<Info>: VPN updated status: Connecting, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|543<Info>: VPN updated status: Connecting, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|553<Info>: VPN updated status: Disconnected, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|553<Info>: VPN updated status: Disconnected, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel start:][34289]|473<Info>: Start vpn: VPN ios 
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|543<Info>: VPN updated status: Connecting, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|543<Info>: VPN updated status: Connecting, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|548<Info>: VPN updated status: Disconnecting, UI delegate = <MVPNConInfoViewController: 0x100a48f20>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|548<Info>: VPN updated status: Disconnecting, UI delegate = <MVPNConInfoViewController: 0x100a48f20>
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|553<Info>: VPN updated status: Disconnected, UI delegate = <MVPNConInfoViewController: 0x100a48f20>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|553<Info>: VPN updated status: Disconnected, UI delegate = <MVPNConInfoViewController: 0x100a48f20>
[MVPNProviderManagerModel appDidEnterBackground:][34289]|94<Info>: App did enter background
[MVPNProviderManagerModel appWillEnterForeground:][34289]|85<Info>: App will enter foreground
[MVPNProviderManagerModel loadManagers][34289]|106<Info>: Start load all provider managers
[MVPNProviderManagerModel loadManagers]_block_invoke[34289]|112<Info>: Load 1 provider managers successfully
[MVPNProviderManagerModel selectedManager][34289]|391<Info>: Get enabled provider manager index(0), total profiles count(1)
[MVPNProviderManagerModel loadManagers][34289]|106<Info>: Start load all provider managers
[MVPNProviderManagerModel loadManagers]_block_invoke[34289]|112<Info>: Load 1 provider managers successfully
[MVPNProviderManagerModel start:][34289]|473<Info>: Start vpn: VPN ios 
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|543<Info>: VPN updated status: Connecting, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|543<Info>: VPN updated status: Connecting, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|543<Info>: VPN updated status: Connecting, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|543<Info>: VPN updated status: Connecting, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|553<Info>: VPN updated status: Disconnected, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|553<Info>: VPN updated status: Disconnected, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|553<Info>: VPN updated status: Disconnected, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|553<Info>: VPN updated status: Disconnected, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel start:][34289]|473<Info>: Start vpn: VPN ios 
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|543<Info>: VPN updated status: Connecting, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|543<Info>: VPN updated status: Connecting, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|543<Info>: VPN updated status: Connecting, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|543<Info>: VPN updated status: Connecting, UI delegate = <MVPNMainViewController: 0x100b0ad80>
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|548<Info>: VPN updated status: Disconnecting, UI delegate = <MVPNConInfoViewController: 0x100b27be0>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|548<Info>: VPN updated status: Disconnecting, UI delegate = <MVPNConInfoViewController: 0x100b27be0>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|548<Info>: VPN updated status: Disconnecting, UI delegate = <MVPNConInfoViewController: 0x100b27be0>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|548<Info>: VPN updated status: Disconnecting, UI delegate = <MVPNConInfoViewController: 0x100b27be0>
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel sendProviderMsg:data:]_block_invoke[34289]|631<Info>: No response from extention
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|553<Info>: VPN updated status: Disconnected, UI delegate = <MVPNConInfoViewController: 0x100b27be0>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|553<Info>: VPN updated status: Disconnected, UI delegate = <MVPNConInfoViewController: 0x100b27be0>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|553<Info>: VPN updated status: Disconnected, UI delegate = <MVPNConInfoViewController: 0x100b27be0>
[MVPNProviderManagerModel observerVPNStatus]_block_invoke_2[34289]|553<Info>: VPN updated status: Disconnected, UI delegate = <MVPNConInfoViewController: 0x100b27be0>
[MVPNProviderManagerModel loadManagers][34289]|106<Info>: Start load all provider managers
[MVPNProviderManagerModel loadManagers]_block_invoke[34289]|112<Info>: Load 1 provider managers successfully
[MVPNProviderManagerModel appDidEnterBackground:][34289]|94<Info>: App did enter background
4]|438<Info>: *** socket_protect 11
|static void CVPNMan::outputLog(const char *)[37894]|433<Info>: Connecting to vpn.testserver.com:8114 (169.38.140.131) via UDPv4
|static void CVPNMan::outputLog(const char *)[37894]|434<Verbose>: Connecting to vpn.testserver.com:8114 (169.38.140.131) via UDPv4
|static void CVPNMan::outputLog(const char *)[37894]|433<Info>: CONNECTING
|static void CVPNMan::outputLog(const char *)[37894]|434<Verbose>: CONNECTING
|static void CVPNMan::outputLog(const char *)[37894]|438<Info>: Tunnel Options:V4,dev-type tun,link-mtu 1570,tun-mtu 1500,proto UDPv4,comp-lzo,cipher AES-256-CBC,auth SHA256,keysize 256,tls-auth,key-method 2,tls-client
10/21/2024 21:58:30|static void CVPNMan::outputLog(const char *)[37894]|438<Info>: Peer Info:
IV_GUI_VER=VPN Client 1.0
IV_VER=3.0
IV_PLAT=ios
IV_NCP=1
IV_LZO_STUB=1
IV_COMP_STUB=1

|static void CVPNMan::outputLog(const char *)[37894]|438<Info>: ERROR: PKTID_UDP_REPLAY
|static void CVPNMan::outputLog(const char *)[37894]|438<Info>: ERROR: REPLAY_ERROR
|static void CVPNMan::outputLog(const char *)[37894]|438<Info>: ERROR: CC_ERROR
|static void CVPNMan::outputLog(const char *)[37894]|438<Info>: ERROR: CC_ERROR
5|static void CVPNMan::outputLog(const char *)[37894]|438<Info>: ERROR: CC_ERROR
|static void CVPNMan::outputLog(const char *)[37894]|438<Info>: ERROR: CC_ERROR
|static void CVPNMan::outputLog(const char *)[37894]|438<Info>: ERROR: CC_ERROR
|static void CVPNMan::outputLog(const char *)[37894]|438<Info>: ERROR: CC_ERROR
|-[PacketTunnelProvider stopTunnelWithReason:completionHandler:][37893]|68<Info>: vpn stopped by provider
```

**Comment by cron2** [comment] 2024-12-11 14:13
This is a duplicate of https://github.com/OpenVPN/openvpn3/discussions/340.

We do not really care very much, tbh.  Just upgrade the iOS client to something not antique, and it will mysteriously start working.

Reasonably up-to-date iOS Connect works just fine against OpenVPN 2.6.x and 2.x master (provided you're not using MD5 or SHA1 certificates).

**Closed by cron2** 2024-12-11 14:13 UTC

**Comment by schwabe** [comment] 2024-12-11 15:00
`tls-cipher TLS-DHE-RSA-WITH-AES-256-CBC-SHA256`

hardcoding tls-cipher is almost always not a good thinhg.
