### ISSUE TITLE
bug in OpenVPN 2.6.1: assert at tls_crypt.c:83 with tls-crypt-v2

### ISSUE THREAD

**Issue by joksik** [OpenVPN/openvpn#272] opened 2023-03-09 07:18 UTC
Hello today i update OpenVPN to newest version OpenVPN-2.6.1-I001-amd64 (under Windows 11 x64) and i can`t connect to any my OpenVPN Server. In logs it stuck with SENT CONTROL:

```
Thu Mar  9 08:11:20 2023 [server_xxx] Peer Connection Initiated with [AF_INET]xx.xx.xx.xx:xxx
Thu Mar  9 08:11:20 2023 TLS: move_session: dest=TM_ACTIVE src=TM_INITIAL reinit_src=1
Thu Mar  9 08:11:20 2023 TLS: tls_multi_process: initial untrusted session promoted to trusted
Thu Mar  9 08:11:21 2023 MANAGEMENT: >STATE:1678345881,GET_CONFIG,,,,,,
Thu Mar  9 08:11:21 2023 SENT CONTROL [server_xxx]: 'PUSH_REQUEST' (status=1)
Thu Mar  9 08:11:27 2023 SENT CONTROL [server_xxx]: 'PUSH_REQUEST' (status=1)
Thu Mar  9 08:11:32 2023 SENT CONTROL [server_xxx]: 'PUSH_REQUEST' (status=1)
Thu Mar  9 08:11:37 2023 SENT CONTROL [server_xxx]: 'PUSH_REQUEST' (status=1)
Thu Mar  9 08:11:42 2023 SENT CONTROL [server_xxx]: 'PUSH_REQUEST' (status=1)
Thu Mar  9 08:11:47 2023 SENT CONTROL [server_xxx]: 'PUSH_REQUEST' (status=1)
Thu Mar  9 08:11:53 2023 SENT CONTROL [server_xxx]: 'PUSH_REQUEST' (status=1)
Thu Mar  9 08:11:58 2023 SENT CONTROL [server_xxx]: 'PUSH_REQUEST' (status=1)
```

when i back to OpenVPN-2.6.0-I005-amd64 everything works so probably something with new version broke connections. i tested under 2.6.1 ovpn-dco and windows-driver wintun and it no works :/ so this is probably not the driver's fault, but the behavior of the program.
full logs from connections:

```
2023-03-09 08:11:19 OpenVPN 2.6.1 [git:v2.6.1/2c2a98a0e559928c] Windows-MSVC [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] [DCO] built on Mar  8 2023
2023-03-09 08:11:19 Windows version 10.0 (Windows 10 or greater), amd64 executable
2023-03-09 08:11:19 library versions: OpenSSL 3.0.8 7 Feb 2023, LZO 2.10
2023-03-09 08:11:19 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:xxx
2023-03-09 08:11:19 Need hold release from management interface, waiting...
2023-03-09 08:11:20 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:xxx
2023-03-09 08:11:20 MANAGEMENT: CMD 'state on'
2023-03-09 08:11:20 MANAGEMENT: CMD 'log on all'
2023-03-09 08:11:20 MANAGEMENT: CMD 'echo on all'
2023-03-09 08:11:20 MANAGEMENT: CMD 'bytecount 5'
2023-03-09 08:11:20 MANAGEMENT: CMD 'state'
2023-03-09 08:11:20 MANAGEMENT: CMD 'hold off'
2023-03-09 08:11:20 MANAGEMENT: CMD 'hold release'
2023-03-09 08:11:20 TCP/UDP: Preserving recently used remote address: [AF_INET]xx.xxx.xxx.xx:xxx
2023-03-09 08:11:20 ovpn-dco device [OpenVPN Data Channel Offload] opened
2023-03-09 08:11:20 UDPv4 link local: (not bound)
2023-03-09 08:11:20 UDPv4 link remote: [AF_INET]xx.xxx.xxx.xx:xxx
2023-03-09 08:11:20 MANAGEMENT: >STATE:1678345880,WAIT,,,,,,
2023-03-09 08:11:20 MANAGEMENT: >STATE:1678345880,AUTH,,,,,,
2023-03-09 08:11:20 TLS: Initial packet from [AF_INET]xx.xxx.xxx.xx:23524, sid=388e6946 10807e6d
2023-03-09 08:11:20 VERIFY OK: depth=1, CN=cn_xxx
2023-03-09 08:11:20 VERIFY KU OK
2023-03-09 08:11:20 Validating certificate extended key usage
2023-03-09 08:11:20 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2023-03-09 08:11:20 VERIFY EKU OK
2023-03-09 08:11:20 VERIFY X509NAME OK: CN=server_xxx
2023-03-09 08:11:20 VERIFY OK: depth=0, CN=server_xxx
2023-03-09 08:11:20 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 256 bit EC, curve prime256v1, signature: ecdsa-with-SHA256
2023-03-09 08:11:20 [server_uKXUBx5dKxTJIEpB] Peer Connection Initiated with [AF_INET]xx.xxx.xxx.xx:xxx
2023-03-09 08:11:20 TLS: move_session: dest=TM_ACTIVE src=TM_INITIAL reinit_src=1
2023-03-09 08:11:20 TLS: tls_multi_process: initial untrusted session promoted to trusted
2023-03-09 08:11:21 MANAGEMENT: >STATE:1678345881,GET_CONFIG,,,,,,
2023-03-09 08:11:21 SENT CONTROL [server_xxx]: 'PUSH_REQUEST' (status=1)
2023-03-09 08:11:27 SENT CONTROL [server_xxx]: 'PUSH_REQUEST' (status=1)
2023-03-09 08:11:32 SENT CONTROL [server_xxx]: 'PUSH_REQUEST' (status=1)
2023-03-09 08:11:37 SENT CONTROL [server_xxx]: 'PUSH_REQUEST' (status=1)
2023-03-09 08:11:42 SENT CONTROL [server_xxx]: 'PUSH_REQUEST' (status=1)
2023-03-09 08:11:47 SENT CONTROL [server_xxx]: 'PUSH_REQUEST' (status=1)
2023-03-09 08:11:53 SENT CONTROL [server_xxx]: 'PUSH_REQUEST' (status=1)
2023-03-09 08:11:58 SENT CONTROL [server_xxx]: 'PUSH_REQUEST' (status=1)
2023-03-09 08:12:03 SENT CONTROL [server_xxx]: 'PUSH_REQUEST' (status=1)
2023-03-09 08:12:07 SIGTERM received, sending exit notification to peer
2023-03-09 08:12:07 Attempting to send data packet while data channel offload is in use. Dropping packet
2023-03-09 08:12:08 SENT CONTROL [server_xxx]: 'PUSH_REQUEST' (status=1)
2023-03-09 08:12:08 Closing DCO interface
2023-03-09 08:12:08 SIGTERM[soft,exit-with-notification] received, process exiting
2023-03-09 08:12:08 MANAGEMENT: >STATE:1678345928,EXITING,exit-with-notification,,,,,
```

**Comment by joksik** [comment] 2023-03-09 09:03
no i dont have the server log it doesn't belong to me but if this is helpful then:
this version works
https://github.com/OpenVPN/openvpn-build/actions/runs/4325757045
this version dont works
https://github.com/OpenVPN/openvpn-build/actions/runs/4368201305

**Comment by joksik** [comment] 2023-03-09 09:11
I was able to replicate the error on a test server machine. the server shows this error:

2023-03-09 10:09:05 us=845014 Initialization Sequence Completed
2023-03-09 10:09:07 us=7045 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:08 us=118374 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:09 us=233427 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:12 us=385434 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:13 us=418444 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:13 us=419325 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:15 us=453486 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:16 us=484976 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:17 us=518171 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:18 us=556324 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:21 us=814344 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:21 us=814598 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:23 us=37947 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:24 us=261323 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:26 us=503307 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:26 us=508298 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:27 us=734051 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:28 us=957889 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:31 us=184874 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:32 us=263385 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:33 us=342980 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:36 us=429454 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:37 us=506044 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:40 us=590509 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:43 us=33897 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:47 us=250999 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:52 us=465445 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:09:56 us=596624 TLS Error: could not determine wrapping from [AF_INET]xx.xxx.xxx.xx:31825
2023-03-09 10:10:03 us=899920 Control Channel: using tls-crypt-v2 key
2023-03-09 10:10:03 us=900040 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
2023-03-09 10:10:03 us=900096 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
2023-03-09 10:10:03 us=900129 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
2023-03-09 10:10:03 us=900207 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
2023-03-09 10:10:03 us=916743 Connection Attempt Control Channel: using tls-crypt-v2 key
2023-03-09 10:10:03 us=916880 Connection Attempt Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
2023-03-09 10:10:03 us=916936 Connection Attempt Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
2023-03-09 10:10:03 us=916966 Connection Attempt Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
2023-03-09 10:10:03 us=917005 Connection Attempt Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
2023-03-09 10:10:03 us=917063 Connection Attempt MULTI: multi_create_instance called
2023-03-09 10:10:03 us=917135 xx.xxx.xxx.xx:52389 Re-using SSL/TLS context
2023-03-09 10:10:03 us=917197 xx.xxx.xxx.xx:52389 tls-crypt-v2 server key: Cipher 'AES-256-CTR' initialized with 256 bit key
2023-03-09 10:10:03 us=917245 xx.xxx.xxx.xx:52389 tls-crypt-v2 server key: Using 256 bit message hash 'SHA256' for HMAC authentication
2023-03-09 10:10:03 us=917595 xx.xxx.xxx.xx:52389 Control Channel MTU parms [ mss_fix:0 max_frag:0 tun_mtu:1250 tun_max_mtu:0 headroom:126 payload:1600 tailroom:126 ET:0 ]
2023-03-09 10:10:03 us=917623 xx.xxx.xxx.xx:52389 Data Channel MTU parms [ mss_fix:0 max_frag:0 tun_mtu:1500 tun_max_mtu:1600 headroom:136 payload:1768 tailroom:562 ET:0 ]
2023-03-09 10:10:03 us=917764 xx.xxx.xxx.xx:52389 Control Channel: using tls-crypt-v2 key
2023-03-09 10:10:03 us=917816 xx.xxx.xxx.xx:52389 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
2023-03-09 10:10:03 us=917856 xx.xxx.xxx.xx:52389 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication

**Comment by schwabe** [comment] 2023-03-09 09:42
Are you able to give me the config that made it fail on your test machine for client and server, so I can try to reproduce it?

**Comment by joksik** [comment] 2023-03-09 09:54
ok.

**client config:**

block-ipv6
windows-driver ovpn-dco
reneg-sec 0
keepalive 15 120
ping-timer-rem
key-direction 1
log "C:\\Program Files\\OpenVPN\\log\\openvpn.log"
float
client
proto udp4
explicit-exit-notify
remote xx.xx.xx.xx 23524
dev tun
resolv-retry infinite
nobind
persist-key
remote-cert-tls server
verify-x509-name server_uKXUBx5dKxTJIEpB name
auth SHA256
auth-nocache
cipher AES-128-GCM
tls-client
tls-version-min 1.3
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256 
ignore-unknown-option block-outside-dns

verb 3
<ca>
</ca>
<cert>
</cert>
<key>
</key>
<tls-crypt-v2>
-----BEGIN OpenVPN tls-crypt-v2 client key-----
-----END OpenVPN tls-crypt-v2 client key-----
</tls-crypt-v2>

**server-config:**

mode server
local 192.168.3.195
block-ipv6
max-clients 50
push "topology subnet"
ifconfig 172.16.1.1 255.255.255.0
ifconfig-pool 172.16.1.10 172.16.1.100 255.255.255.0
push "explicit-exit-notify 3"

push "register-dns"
push "dhcp-option DNS 192.168.2.211"
push "dhcp-option DOMAIN ad.my.domain.pl"

push "route-gateway 172.16.1.1"

port 23524
proto udp4
dev tun
persist-key
persist-tun
keepalive 10 120
topology subnet
ifconfig-pool-persist ipp.txt

dh none
tls-groups prime256v1
tls-crypt-v2 'keys-v2/tls-crypt-server-v2.key'
crl-verify crl.pem
ca ca.crt
cert server_uKXUBx5dKxTJIEpB.crt
key server_uKXUBx5dKxTJIEpB.key
auth SHA256
cipher AES-128-GCM
data-ciphers AES-128-GCM
tls-server
tls-version-min 1.3
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
client-config-dir /etc/openvpn/ccd
status /var/log/openvpn/status.log
log /var/log/openvpn/openvpn.log
log-append /var/log/openvpn/openvpn.log
verb 4

**Comment by schwabe** [comment] 2023-03-09 10:35
Thanks. I can reproduce the issue and will send a fix soon.

**Comment by schwabe** [comment] 2023-03-09 14:12
Fix here: https://patchwork.openvpn.net/project/openvpn2/patch/20230309120031.3780130-1-arne@rfc2549.org/

**Comment by joksik** [comment] 2023-03-10 06:23
i downloaded **artifacts-x64.zip** from https://github.com/OpenVPN/openvpn/actions/runs/4377815367 I replaced the files in C:\Program Files\OpenVPN\bin and still not works the same behavior.

**Comment by schwabe** [comment] 2023-03-10 09:11
The server side crashes, not the client side.

**Comment by joksik** [comment] 2023-03-10 09:40
ok thx. so i must wait for new .deb file to test ;) if someone will upload fixed version to testing openvpn repo i will be glad.

https://build.openvpn.net/debian/openvpn/testing/pool/kinetic/main/o/openvpn/

**Comment by cron2** [comment] 2023-03-24 17:06
2.6.2 has been released, including debian builds.

**Comment by cron2** [comment] 2023-04-11 15:33
Hi,

On Fri, Mar 10, 2023 at 01:40:30AM -0800, joksik wrote:
> ok thx. so i must wait for new .deb file to test ;) if someone will upload fixed version to testing openvpn repo i will be glad.

2.6.2 .deb have been uploaded - can you test that everything works for
you now, and then close the issue, please?

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by schwabe** [comment] 2023-05-16 11:43
Closing this issue since the issue is believed to be resolved in newer versions.

**Closed by schwabe** 2023-05-16 11:43 UTC
Labels: bug
